# Generated by Django 5.2.13 on 2026-04-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
